version: '3.8'

services:
  db:
    image: doctorkirk/oracle-19c
    container_name: oracle19c
    ports:
      - ${DB_BINDING_PORT}:${DB_PORT}
    restart: always
    environment:
      ORACLE_SID: ${ORACLE_SID}
      ORACLE_PWD: ${ORACLE_PWD}
      ORACLE_CHARACTERSET: ${ORACLE_CHARACTERSET}
    volumes:
      - ${DB_LOCAL_DIRECTORY}:${DB_IMAGE_DIRECTORY}

  redis:
    image:
      redis:7.2.4
    ports:
      - ${REDIS_BINDING_PORT}:${REDIS_PORT}
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ${REDIS_DATA_PATH}:/data
      - ${REDIS_DEFAULT_CONFIG_FILE}:/usr/local/etc/redis/redis.conf
    restart: always